### ISSUE TITLE
Add a third-party integration to Algorithmia

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/integrations#1]
[Algorithmia](https://algorithmia.com) lets you add the power of serverless machine-learning and utility microservices to almost any other service / application. A wide variety of [algorithms](https://algorithmia.com/algorithms/) algorithms are available, and can be called via POST or from various [language clients](https://algorithmia.com/developers/clients/).

For one example, see [RunDexter](https://github.com/algorithmiaio/integrations/tree/master/RunDexter). Due to the nature of Dexter's bots, this sample is a set of cut-and-paste code templates. However, other solutions might include full-featured plugins, app project files, or even machine instances.

If you don't yet have an Algorithmia account, [sign up](https://algorithmia.com/signup/) with the promo code `Hacktoberfest` for $50 in free credits.  And don't forget to register at http://hacktoberfest.digitalocean.com to get a free t-shirt!

Then, select any third-party service you find interesting, and add whatever form of integration you feel would be most useful. We'll feature the best ones on our [blog](http://blog.algorithmia.com), and drop a bunch of extra credits in your account as a thank-you gift!

By the way:
- please include a `README.md` describing what your contribution does, and how to run it
- be careful not to include any API Keys or other secure information (it is common practice to use `YOUR_API_KEY` in code samples to represent an Algorithmia API Key

Thanks for your help!

**Comment by MikeyAnderson** [comment]
Looks good to me.
