### ISSUE TITLE
Create plugin for Adobe Photoshop [$500]

### ISSUE THREAD

**Issue by peckjon** [algorithmiaio/integrations#5]
Algorithmia hosts a wide variety of APIs for image modification and data extraction: https://algorithmia.com/tags/computer-vision

Make it possible to use these APIs directly from within Photoshop.  At minimum, this should be a graphical tool which allows users to:

- set their Algorithmia API Key (located at https://algorithmia.com/user#credentials once the user has signed up)
- pick an image to send to Algorithmia's APIs (likely this is a single Layer or a Selection, but open to suggestions)
- pick which API/Algorithm to run on the image (possibly a simple selector for basic routines like Colorize, plus an advanced option to allow them to run any Algorithm by entering its URL and parameters)

<img width="982" alt="select an algorithm" src="https://user-images.githubusercontent.com/5299412/34121777-0776081e-e3df-11e7-8312-d5f83b327827.png">

**Comment by ghost** [comment]
@peckjon I'd like to contribute to this project - my solution will be targeting Photoshop CC, using CEP 8.0; is this subject still relevant at present?

**Comment by peckjon** [comment]
Absolutely — thanks @denim2x !

Shoot me an email at jpeck@algorithmia.io and we’ll sync up!

**Comment by ghost** [comment]
you can track my progress [here](https://github.com/denim2x/algorithmia-cep/projects/1); the Gitter channel is [here](https://gitter.im/algorithmia-cep/Lobby)
